name: Cypress end-to-end Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:

  # install:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node12.18.3-chrome87-ff82
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Cypress install
  #       uses: cypress-io/github-action@v4
  #       with:
  #         # Disable running of tests within install job
  #         runTests: false
  #         build: yarn build

  #     - name: Save build folder
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: build
  #         if-no-files-found: error
  #         path: build

  cypress-e2e:
    runs-on: ubuntu-latest
    #container: cypress/browsers:node12.18.3-chrome87-ff82
    #needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]

    services:
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025 # smtp server
          - 8025:8025 # web ui

      postgres:
        image: postgres
        env:
          POSTGRES_DB: default
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
          TZ:  Europe/Warsaw
        ports:
          - 5432:5432

      
      api: 
        image: escolalms/api:latest
        ports:
          - 80:80

        options: >-
          --name api 



    steps:

      - run: docker exec api ls

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

          

          

           # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      #- name: Cypress run
      #  uses: cypress-io/github-action@v4