# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  #  jest:
  #    runs-on: ubuntu-latest

  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Use Node.js
  #        uses: actions/setup-node@v1
  #        with:
  #          node-version: '14.x'
  #      - run: npm i
  #      - run: npm run test

  #      - name: Code Coverage upload
  #        uses: codecov/codecov-action@v1
  #        with:
  #          files: ./coverage/clover.xml # optional

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: Lint test ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn lint:js

  tsc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    name: TypeScript test ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn
      - run: NODE_OPTIONS='--max-old-space-size=16384' yarn tsc:noemit
